// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20230221113519_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Data.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Data.Models.CartProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("CpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CpuType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("GpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GpuType")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Inch")
                        .HasColumnType("float");

                    b.Property<bool>("IsOrderd")
                        .HasColumnType("bit");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("int");

                    b.Property<int>("MilliampHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationSystem")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Panel")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.Property<int>("SizeMM")
                        .HasColumnType("int");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("Data.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<int>("Month_ExpirationDate")
                        .HasColumnType("int");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<int>("Year_ExpirationDate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsShipped")
                        .HasColumnType("bit");

                    b.Property<bool>("Open")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreditCardId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("CpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CpuType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("GpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GpuType")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Inch")
                        .HasColumnType("float");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("int");

                    b.Property<int>("MilliampHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationSystem")
                        .HasColumnType("int");

                    b.Property<int>("Panel")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.Property<int>("SizeMM")
                        .HasColumnType("int");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The PlayStation 5 (PS5) is a home video game console developed by Sony Interactive Entertainment. It was announced as successor to the PlayStation 4 in April 2019, was launched on November 12, 2020",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.citypng.com/public/uploads/preview/-11591925787cggjhepdvq.png",
                            Inch = 0.0,
                            Manufacturer = 5,
                            MilliampHours = 0,
                            Name = "PlayStation 5",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 499,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2792),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The PlayStation 4 (PS4) is a home video game console developed by Sony Interactive Entertainment.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.seekpng.com/png/full/199-1998029_playstation4-vinyl-decal-stickers-for-ps4-game-console.png",
                            Inch = 0.0,
                            Manufacturer = 5,
                            MilliampHours = 0,
                            Name = "PlayStation 4",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 299,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2828),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Xbox Series X is launching at participating retailers worldwide on 10 November 2020.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4mRni?ver=a707",
                            Inch = 0.0,
                            Manufacturer = 6,
                            MilliampHours = 0,
                            Name = "Xbox Series X",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 329,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2830),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Xbox One S is launching at participating retailers worldwide on 10 Aogust 2019.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.skinit.com/media/wysiwyg/category/skins/gaming-skins/microsoft/xbox-one-s-desktop.png",
                            Inch = 0.0,
                            Manufacturer = 6,
                            MilliampHours = 0,
                            Name = "Xbox ",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 329,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2831),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "iPhone 12 includes a faster and more powerful Image Signal Processor that enabled new camera functionality for 2020",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://pngimg.com/d/iphone_12_PNG3.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 12",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 699,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2833),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "iPhone 12 pro includes a faster and more powerful Image Signal Processor that enabled new camera functionality for 2020",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://assets.swappie.com/cdn-cgi/image/width=600,height=600,fit=contain,format=auto/swappie-iphone-12-pro-max-graphite.png?v=13",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 12 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2834),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "iPhone 12 max includes a faster and more powerful Image Signal Processor that enabled new camera functionality for 2020.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://pngimg.com/uploads/iphone_12/iphone_12_PNG3.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 12 Max",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2836),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPhone 13 and iPhone 13 Mini (stylized as iPhone 13 mini) are smartphones designed, developed, markete.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.dailyobjects.com/marche/product-images/1101/slick-phone-case-cover-for-iphone-13-images/Nimbus-Phone-Case-Cover-For-iPhone-13.png?tr=cm-pad_resize,v-2",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 13",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2837),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPhone 13 and iPhone 13 Mini (stylized as iPhone 13 mini) are smartphones designed, developed, marketed.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.pngmart.com/files/21/iPhone-13-Pro-PNG-Image.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 13 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2838),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPhone 13 and iPhone 13 Mini (stylized as iPhone 13 mini) are smartphones designed, developed, marketed",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-max-silver-select?wid=940&hei=1112&fmt=png-alpha&.v=1631652956000",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 13 Max",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2839),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple's iPhone 14 models are identical in design to the iPhone 13 models, featuring flat edges, an aerospace-grade aluminum enclosure, and a glass back that enables wireless charging",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://png.monster/wp-content/uploads/2022/09/png.monster-209.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 14 ",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2840),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple's iPhone 14 models are identical in design to the iPhone 13 models, featuring flat edges, an aerospace-grade aluminum enclosure, and a glass back that enables wireless charging",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://s7d1.scene7.com/is/image/dish/iPhone_14_Pro_Deep_Purple_phonewall?$ProductBase$",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 14 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2841),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple's iPhone 14 models are identical in design to the iPhone 13 models, featuring flat edges, an aerospace-grade aluminum enclosure, and a glass back that enables wireless charging",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://assets.swappie.com/cdn-cgi/image/width=600,height=600,fit=contain,format=auto/swappie-iphone-14-pro-max-gold-back.png?v=13",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 14 Max",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2843),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S21 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/il/galaxy-s21/gallery/il-galaxy-s21-5g-g991-sm-g991bzadmec-359240688",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S21",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2844),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S21 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/sg/galaxy-s21/gallery/sg-galaxy-s21-5g-g996-sm-g996bzsgxsp-368336436?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S21+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2845),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S21 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/ca/galaxy-s21/gallery/ca-galaxy-s21-ultra-5g-g988-sm-g998wzkaxac-thumb-368336282",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S21 Ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2847),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0552/5821/8633/products/96c7b58c6fadffd51dc61cea80e2901d.png?v=1666343215",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S22",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2848),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22+ is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/9279758/large/bc931c6792b57d70fcffdd20939e018e.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S22+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2849),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 ultra is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://media.bechtle.com/is/180712/1c4b3d4ee288fc9434f5175bf56070570/c3/gallery/1200cd0e901a448ab8c94e14a710c1b4?version=0",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S22 ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2850),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://nextech.co.il/wp-content/uploads/2023/02/green-8.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S23",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2851),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22+ is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/9279758/large/bc931c6792b57d70fcffdd20939e018e.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S23+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2852),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 ultra is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.att.com/idpassets/global/devices/phones/samsung/samsung-galaxy-s23-ultra/carousel/phantomblack/phantomblack-4.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S23 ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2855),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Xiaomi 11s is a good all-rounder. It's powerful, the camera produces nice images during the day and night, and the screen is superior to phone mid-rangers, with more pixels and above-average brightness. While the battery life is not standard-setting, it's solid, and the charging speed is excellent.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.bug.co.il/images/site/products/e275ec4b-eeab-4345-b35f-05b8233f031f.png",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "Xiaomi Note 11 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2856),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Xiaomi 11 pro is a good all-rounder. It's powerful, the camera produces nice images during the day and night, and the screen is superior to phone mid-rangers, with more pixels and above-average brightness. While the battery life is not standard-setting, it's solid, and the charging speed is excellent.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "http://i01.appmifile.com/webfile/globalimg/pic/Redmi-Note-11S-Blanco-Perla!800x800!85.png",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "Xiaomi Note 11S",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2857),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Xiaomi 11 is a good all-rounder. It's powerful, the camera produces nice images during the day and night, and the screen is superior to phone mid-rangers, with more pixels and above-average brightness. While the battery life is not standard-setting, it's solid, and the charging speed is excellent.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/11206223/large/a56d598ce836e66e4b62f2272802da0b.png",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "Xiaomi Note 11",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2858),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The biggest and brightest Apple Watch display. The Always‑On Retina display is 2000 nits at its peak and twice as bright as any other Apple Watch. The bigger display provides more room for workout metrics and detail‑packed watch faces.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0157/3520/products/NM00736685_0007_855848007366_A2-PhotoRoom.png?v=1664873211",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2859),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/s/t/starlight_1_2.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch series 8 41mm",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 650,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2889),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/m/i/midnight02_1.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch series 8 45mm",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 550,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2892),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MPLT3ref_VW_PF+watch-44-alum-midnight-nc-se_VW_PF_WF_SI?wid=2000&hei=2000&fmt=png-alpha&.v=1660778411615,1660759426989",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch se",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 500,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2893),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://api.sammobile.com/static/3-027_product_galaxy_watch5pro_blacktitanium_r_perspective_LI.png?1660133183",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung watch 5 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 930,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2894),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/ph/2208/gallery/ph-galaxy-watch5-44mm-sm-r910nzaaasa-533197643?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung watch 5",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2895),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/my/2108/gallery/my-galaxy-watch4-classic-398835-sm-r890nzkaxme-481102149?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung watch 4 classic",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 650,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2897),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Description. The iPad Pro 12.9-inch (2022) comes with 12.9-inch display and Apple's M2 processor. Specs also include Dual camera setup on the back with 12MP main sensor and up to 16GB RAM and 2TB internal storage.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.firstnet.com/content/dam/firstnet/images/tablets-and-laptops/firstnet-apple-ipad-pro-12-9-in-2022.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad pro 12.9",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1199,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2898),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The 11-inch iPad Pro display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 11 inches diagonally (actual viewable area is less).",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.theiphonewiki.com/w/images/thumb/1/14/IPadPro_11-inch_2nd_generation.png/300px-IPadPro_11-inch_2nd_generation.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad pro 11",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 999,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2899),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "In theory, the ‌iPad Air‌ is a more compelling package with the ‌M1‌ chip, 4GB of additional memory, a dedicated media engine, ‌Stage Manager‌ for multitasking, a better display, and a much better ‌Apple Pencil‌ experience, but in practice, users are unlikely to notice much difference between the devices.9 2022",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://pro-digital.co.il/wp-content/uploads/2021/11/8901a1969a9b3023daf14443ac4d7225.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad Air 10.9",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1000,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2900),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The stunning 10.9-inch Liquid Retina display makes an incredible canvas. So you can doodle, take notes, mark up documents, and a lot more with Apple Pencil. Record and refine from anywhere with high-quality built-in mics and landscape stereo speakers.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/9055438/large/e81a08e554af37be8a6d600824a29e57.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad 10.9",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1169,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2901),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPad 10.2 (2021) is offering 10.2 inch display that supports Apple Pencil and it has Wi-Fi only model or with LTE enabled. The tablet comes with 8526mAh battery, Apple A13 Bionic processor and offers two internal storage variants - 64GB or 256GB. Prices start from $329.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/h/6/h69114077_1000x1000_2.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad 10.2",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2903),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/sg/sm-x906bzajxsp/gallery/sg-galaxy-tab-s8-ultra-5g-x906-sm-x906bzajxsp-534194325?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab S8 Ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1299,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2905),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://res-1.cloudinary.com/grover/image/upload/v1646833195/cieclvic1gpo7h7sqgyv.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab 8+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 889,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2907),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/8705804/original/f4a99cf07a6c9ec750e0e18778d64bb0.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab A8",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2908),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/e/0/e010022011_3_1_1_1.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab A7 Lite",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2909),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Colors matched to a vibrant and vivid image\r\nExperience vivid colors as they are designed to be in powerful 4K\r\n4K crystal processor\r\nA powerful 4K upgrade ensures that you get a resolution of up to 4K for the content you like. You will also experience more vivid color expressions thanks to its sophisticated color mapping technology.\r\n\r\n Feel a vivid hue of color as it is designed to be in powerful 4K\r\nSmooth motion for a clear image\r\nMotion Xcelerator\r\nCome experience clear images and performance because it automatically evaluates and compensates for frames for the content source.\r\n\r\nSmooth motion for a clear image\r\nFeel the reality of 4K UHD resolution\r\n4K resolution\r\n4K UHD TV transcends regular FHD with 4x more pixels, and offers your eyes the sharp and clear images they deserve. Now you can see even the small details in the scene.\r\n\r\nFeel the reality of 4K UHD resolution\r\nSee darkness and light in every scene\r\nHDR\r\nHigh dynamic range increases the light level range of your TV so you can enjoy a huge rainbow of colors and all the visual details, even in the darkest scenes.\r\n\r\n* The viewing experience may vary depending on the content types and format.\r\n\r\n See darkness and light in every scene\r\nThe TV and sound projector blend in perfect harmony\r\nQ-Symphony\r\nSurround yourself with sound from the TV and sound projector that blend in harmoniously. Q-Symphony is unique in that it allows the TV speakers and the sound projector to operate simultaneously, for a better surround effect without muting the TV speakers.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/8/8/0/7/70817088c.gif",
                            Inch = 75.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung TV 4K 75",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 959,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2911),
                            Resolution = 5,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/7/7/5/0/74830577c.gif",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "LG TV 4K 65",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 699,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2912),
                            Resolution = 5,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/4/0/2/1/64971204c.gif",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "Xiaomi Mi TV 4K 43",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 499,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2914),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/7/2/3/2/70702327c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung TV 4K 50",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 529,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2915),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/7/4/8/4/74324847c.gif",
                            Inch = 0.0,
                            Manufacturer = 5,
                            MilliampHours = 0,
                            Name = "Sony 4K 75",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1159,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2916),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/4/2/6/1/67931624c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Hisense 4K 50",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 319,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2917),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/6/9/3/2/56802396c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung HD 32",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 129,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2918),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/6/3/6/3/69943636c.gif",
                            Inch = 0.0,
                            Manufacturer = 5,
                            MilliampHours = 0,
                            Name = "Sony 4K 100",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 12259,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2919),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/2/6/0/1/69131062c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "TCL 4K 98",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 4999,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2920),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 51,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/8/2/0/4/70674028c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung TV 4K 85",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2923),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 52,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/1/8/5/8/53818581c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Hisense 4K 85",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1999,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2924),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 53,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/2/1/9/5/67935912c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "TCL FullHD 40",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 239,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2926),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 54,
                            Category = 4,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.zap.co.il/pics/5/5/6/9/56109655c.gif",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "MAG HD 32",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 199,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2927),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 55,
                            Category = 8,
                            Color = 7,
                            Cores = 8,
                            CpuType = 5,
                            Description = "MacBook AirPower. It's in the Air.Our thinnest, lightest notebook, completely transformed by the Apple M1 chip. CPU speeds up to 3.5x faster. GPU speeds up to 5x faster. Our most advanced Neural Engine for up to 9x faster machine learning. The longest battery life ever in a MacBook Air. And a silent, fanless design. This much power has never been this ready to go.Small chip. Giant leap.It's here. Our first chip designed specifically for Mac. Packed with an astonishing 16 billion transistors, the Apple M1 system on a chip (SoC) integrates the CPU, GPU, Neural Engine, I/O, and so much more onto a single tiny chip. With incredible performance, custom technologies, and industry-leading power efficiency, M1 is not just a next step for Mac - it's another level entirely.CPU8-core CPU Devours tasks. Sips battery.M1 has the fastest CPU we've ever made. With that kind of processing speed, MacBook Air can take on new extraordinarily intensive tasks like professional-quality editing and action-packed gaming. But the 8-core CPU on M1 isn't just up to 3.5x faster than the previous generation - it balances high-performance cores with efficiency cores that can still crush everyday jobs while using just a tenth of the power.All-day battery lifeUp to 18 hours of battery life. That's 6 more hours, free of charge.Thermal efficiency No fan. No noise. Just Air.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "http://cdn.shopify.com/s/files/1/0183/5769/products/Macbook-Air_0002_438554-Product-0-I-637205827845419382_800x800_66570486-c29a-46f5-9984-c6d6f7446bef.png?v=1618283708",
                            Inch = 13.300000000000001,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Macbook Air M1",
                            OperationSystem = 6,
                            Panel = 6,
                            Price = 899,
                            ReleaseDate = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 56,
                            Category = 8,
                            Color = 7,
                            Cores = 10,
                            CpuType = 6,
                            Description = "The MacBook Pro M1 had a release date of November 17 and starts at $1,299. That configuration gives you Apple’s powerful M1 chip with an 8-core CPU and 8-core GPU, plus 8GB of unified memory (RAM). You get 256GB of storage to start, but the $1,499 model of the MacBook Pro M1 includes 512GB of storage. \r\n\r\nIf you want to configure the MacBook Pro M1 yourself, there are a number of upgrades available. It costs $200 to go from 8GB to 16GB of memory. If you want more than 512GB of storage, 1TB costs an extra $400 while 2TB will run you $800.\r\n\r\nThe MacBook Pro 2021, though looks to seriously improve on the current model. Rumors suggest Apple will bring back MagSafe charging and the SD memory reader, and drop the Touch Bar. All while adding in faster processors and adopting the flat-edge design language of the iPhone 12 and iPad Pro. ",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://telecomtalk.info/wp-content/uploads/2023/02/apple-discontinues-macbook-pro-14-and-16.jpg",
                            Inch = 16.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Macbook Pro M1",
                            OperationSystem = 6,
                            Panel = 6,
                            Price = 1299,
                            ReleaseDate = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 57,
                            Category = 8,
                            Color = 7,
                            Cores = 10,
                            CpuType = 8,
                            Description = "MacBook AirPower. It's in the Air.Our thinnest, lightest notebook, completely transformed by the Apple M1 chip. CPU speeds up to 3.5x faster. GPU speeds up to 5x faster. Our most advanced Neural Engine for up to 9x faster machine learning. The longest battery life ever in a MacBook Air. And a silent, fanless design. This much power has never been this ready to go.Small chip. Giant leap.It's here. Our first chip designed specifically for Mac. Packed with an astonishing 16 billion transistors, the Apple M1 system on a chip (SoC) integrates the CPU, GPU, Neural Engine, I/O, and so much more onto a single tiny chip. With incredible performance, custom technologies, and industry-leading power efficiency, M1 is not just a next step for Mac - it's another level entirely.CPU8-core CPU Devours tasks. Sips battery.M1 has the fastest CPU we've ever made. With that kind of processing speed, MacBook Air can take on new extraordinarily intensive tasks like professional-quality editing and action-packed gaming. But the 8-core CPU on M1 isn't just up to 3.5x faster than the previous generation - it balances high-performance cores with efficiency cores that can still crush everyday jobs while using just a tenth of the power.All-day battery lifeUp to 18 hours of battery life. That's 6 more hours, free of charge.Thermal efficiency No fan. No noise. Just Air.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.ksp.co.il/item/217286/b_1.jpg?v=5",
                            Inch = 14.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Macbook Air M2",
                            OperationSystem = 6,
                            Panel = 6,
                            Price = 999,
                            ReleaseDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 58,
                            Category = 8,
                            Color = 7,
                            Cores = 12,
                            CpuType = 8,
                            Description = "The MacBook Pro M2 had a release date of November 17 and starts at $1,299. That configuration gives you Apple’s powerful M1 chip with an 8-core CPU and 8-core GPU, plus 8GB of unified memory (RAM). You get 256GB of storage to start, but the $1,499 model of the MacBook Pro M1 includes 512GB of storage. \r\n\r\nIf you want to configure the MacBook Pro M1 yourself, there are a number of upgrades available. It costs $200 to go from 8GB to 16GB of memory. If you want more than 512GB of storage, 1TB costs an extra $400 while 2TB will run you $800.\r\n\r\nThe MacBook Pro 2021, though looks to seriously improve on the current model. Rumors suggest Apple will bring back MagSafe charging and the SD memory reader, and drop the Touch Bar. All while adding in faster processors and adopting the flat-edge design language of the iPhone 13 and iPad Pro. ",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.ksp.co.il/item/243844/b_1.jpg?v=5",
                            Inch = 16.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Macbook Pro M2",
                            OperationSystem = 6,
                            Panel = 6,
                            Price = 1499,
                            ReleaseDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 59,
                            Category = 8,
                            Color = 5,
                            Cores = 0,
                            CpuType = 3,
                            Description = "The HP Spectre line is second to none when it comes to design, and this latest model is no exception. Like its 13-inch predecessor, the Spectre x360 14 is made of CNC-machined aluminum. Also like its siblings, you can get the 14 in “nightfall black,” “Poseidon blue,” or “natural silver.” Take a look at some pictures before selecting your color because they each have pretty different vibes. The nightfall black option has a sophisticated, svelte aesthetic that looks tailor-made for a boardroom. Poseidon blue is friendlier and probably the one I’d go for myself. \r\n\r\nThe accents, though, are what make the Spectre stand out from the legions of other black laptops out there. Lustrous trim borders the lid, the touchpad, and the deck. The hinges share its color, as does the HP logo on its lid. It’s bold without being obnoxious. The two rear corners are diamond-shaped, and one of them houses a Thunderbolt 4 port on its flat edge. (On the sides live an audio jack, a USB-A, a microSD slot, and an additional Thunderbolt 4, which is a decent selection — gone is the trapdoor that covered the USB-A port on the 13-inch model.) And the edges are all beveled, making the notebook appear thinner than it actually is (it’s 0.67 inches thick). Careful craftsmanship is evident here",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img.ksp.co.il/item/245647/b_6.jpg?v=5",
                            Inch = 0.0,
                            Manufacturer = 8,
                            MilliampHours = 0,
                            Name = "Spectre x360",
                            OperationSystem = 3,
                            Panel = 0,
                            Price = 1259,
                            ReleaseDate = new DateTime(2023, 2, 21, 13, 35, 18, 877, DateTimeKind.Local).AddTicks(2934),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Data.Models.UserApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Data.Models.CartProduct", b =>
                {
                    b.HasOne("Data.Models.Cart", "Cart")
                        .WithMany("Products")
                        .HasForeignKey("CartId");

                    b.HasOne("Data.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.HasOne("Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Data.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId");

                    b.Navigation("Address");

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("Data.Models.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
